In [31]:
# -*- coding: utf-8 -*-

import numpy as np
import pandas as pd
import datetime
import csv

In [7]:
today = datetime.date.today()
print(today)

yesterday = today - datetime.timedelta(days=1)
print(yesterday)

date = u'調査対象日: ' + str(yesterday)
print(date)

2017-04-15
2017-04-14
調査対象日: 2017-04-14


In [35]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
f = open('test.txt', 'w')
f.write(date + '\n\n')
f.write(u'viewer_id,対象日バトル回数, 0ターン勝利回数(3回以上)\n')
writer = csv.writer(f)
writer.writerows(data)
f.close()

In [46]:
f = open('test2.txt', 'w', newline='')    #newline=''を追加した
f.write(date + '\n\n')
f.write(u'viewer_id,対象日バトル回数, 0ターン勝利回数(3回以上)\n')
writer = csv.writer(f)
writer.writerows(data)
f.close()

In [47]:
with open('test3.txt', 'w', newline='') as f:    #newline=''を追加した
    f.write(date + '\n\n')
    f.write(u'viewer_id,対象日バトル回数, 0ターン勝利回数(3回以上)\n')
    writer = csv.writer(f)
    writer.writerows(data)